version: "3.8"
services:
  shopping-db:
    container_name: shopping-db
    image: mysql:8.0.34
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ./infra/mysql/initdb.d:/docker-entrypoint-initdb.d

