server:
  port: 8080
spring:
  profiles:
    active: '${SPRING_PROFILES_ACTIVE:local}'
  application:
    name: spring-shopping
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
  datasource:
    url: '${DATASOURCE_HOST:jdbc:mysql://localhost:3306/shopping}'
    username: '${DATASOURCE_USERNAME:root}'
    password: '${DATASOURCE_PASSWORD:1234}'
    driver-class-name: '${DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}'
  data:
    redis:
      host: '${REDIS_HOST:localhost}'
      port: '${REDIS_PORT:6379}'
  flyway:
    enabled: true
  rabbitmq:
    host: '${RABBIT_MQ_HOST:localhost}'
    port: '${RABBIT_MQ_PORT:5672}'
    username: '${RABBIT_MQ_USERNAME:admin}'
    password: '${RABBIT_MQ_PASSWORD:admin}'
  kafka:
    producer:
      bootstrap-servers: '${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}'
      transaction-id-prefix: tx-
    consumer:
      properties:
        isolation.level: '${KAFKA_ISOLATION_LEVEL:read_committed}'
      enable-auto-commit: false
      auto-offset-reset: earliest
springdoc:
  version: '@project.version@'
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  show-actuator: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none
  paths-to-match:
    - /api/**
  api-docs:
    enabled: true
management:
  server:
    port: 1${server.port}
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      base-path: /prefer
      exposure:
        exclude:
        include: prometheus, openapi, swagger-ui
    jmx:
      exposure:
        exclude:
        include: prometheus, openapi, swagger-ui
service:
  abusing:
    url: '${SERVICE_ABUSING_URL:https://www.purgomalum.com/service/json?text=}'