spring:
  application:
    name: spring-shopping
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/shopping
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver