spring:
  application:
    name: spring-shopping
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3306/shopping
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
  flyway:
    enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        enable.idempotence: true
        transactional.id: shopping-producer
service:
  abusing:
    url: https://www.purgomalum.com